services:
  - type: web
    name: sync-music-backend
    runtime: node
    repo: https://github.com/Prithviraj-kumar/sync-music-app
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: PORT
        value: 8001
      - key: CORS_ORIGINS
        value: "*"
    plan: free